search:
  base_url: "https://www.linkedin.com/jobs/search/"
  start_param: "start"
  page_size: 25
  extra_params:
    origin: "JOBS_HOME_KEYWORD_AUTOCOMPLETE"
    refresh: "true"
rate_limits:
  page_delay_seconds: 3
selectors:
  job_cards:
    - "[data-occludable-job-id]"
  title:
    - "a.job-card-container__link strong"
  company:
    - "a.job-card-container__company-name"
    - "span.job-card-container__primary-description"
    - "a.base-card__subtitle"
  company_links:
    - "a[href*='linkedin.com/company/']"
    - "a[href*='/company/']"
    - "a[data-tracking-control-name*='company']"
    - ".jobs-unified-top-card__primary-description a[href*='linkedin.com/company/']"
  posting_time:
    - "div.mt2:nth-child(1) > span:nth-child(1) > span:nth-child(3)"
